#define MSG_UNAVAILABLE "Routine Temporaily Unavailable"
#define CLIENT_CLASS    "GENERIC Class"
#define TITLE           "Generic - (C)opyright, 1992 - Gene Backlin"
#define HELPFILE        "GENERIC.HLP"

#define ID_RESOURCE                    100
#define ID_MENU_RESOURCE               110

#define IDM_DISPLAY                    1000
#define IDM_DIS_GENERIC                1001

#define IDM_EXIT                       1800

#define IDM_HELP                       1900
#define IDM_HEL_SEP1                   1901
#define IDM_HEL_ABOUT                  1910
#define IDM_HELP_FOR_HELP              1911
#define IDM_MENU_EXTENDED_HELP         1912
#define IDM_EXTENDED_HELP              ID_MENU_RESOURCE

#define MAIN_HELPTABLE                 2000
#define SUBTABLE_OPTION                2001

#define IDM_HELP_DISPLAY               IDM_DISPLAY
#define IDM_HELP_GENERIC               IDM_DIS_GENERIC
#define IDM_HELP_EXIT                  IDM_EXIT
#define IDM_HELP_HELP                  IDM_HELP
#define IDM_HELP_MENU_EXTENDED_HELP    IDM_MENU_EXTENDED_HELP
#define IDM_HELP_HELP_FOR_HELP         IDM_HELP_FOR_HELP

#define IDD_ABOUTBOX                   3000

#define IDD_DIS_GENERIC                4000
#define IDD_DIS_GENERIC_HELP           4099

